[CmdletBinding()]
param(
    [ValidateSet("check", "restore", "restore-memory", "restore-instructions")]
    [string]$Action = "check",
    [switch]$Apply,
    [string]$CodexHome = (Join-Path $env:USERPROFILE ".codex"),
    [string]$ClaudeHome = (Join-Path $env:USERPROFILE ".claude")
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path $PSScriptRoot -Parent
$portableAgents = Join-Path $repoRoot "global\AGENTS.md"
$portableConfig = Join-Path $repoRoot "global\behavior-config.toml"
$portableSkills = Join-Path $repoRoot "skills"

function Read-SimpleTomlValues([string]$Path) {
    $values = @{}
    $section = ""

    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) {
            continue
        }
        if ($trimmed -match '^\[([^\]]+)\]$') {
            $section = $Matches[1]
            continue
        }
        if ($trimmed -match '^([A-Za-z0-9_.-]+)\s*=\s*(.+)$') {
            $values["$section|$($Matches[1])"] = $Matches[2].Trim()
        }
    }

    return $values
}

function Set-SimpleTomlValue(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Section,
    [string]$Key,
    [string]$Value
) {
    $sectionStart = 0
    $sectionEnd = $Lines.Count

    if ($Section) {
        $header = "[$Section]"
        $headerIndex = -1
        for ($index = 0; $index -lt $Lines.Count; $index++) {
            if ($Lines[$index].Trim() -eq $header) {
                $headerIndex = $index
                break
            }
        }

        if ($headerIndex -lt 0) {
            if ($Lines.Count -gt 0 -and $Lines[$Lines.Count - 1].Trim()) {
                $Lines.Add("")
            }
            $Lines.Add($header)
            $Lines.Add("$Key = $Value")
            return
        }

        $sectionStart = $headerIndex + 1
        for ($index = $sectionStart; $index -lt $Lines.Count; $index++) {
            if ($Lines[$index].Trim() -match '^\[') {
                $sectionEnd = $index
                break
            }
        }
    } else {
        for ($index = 0; $index -lt $Lines.Count; $index++) {
            if ($Lines[$index].Trim() -match '^\[') {
                $sectionEnd = $index
                break
            }
        }
    }

    for ($index = $sectionStart; $index -lt $sectionEnd; $index++) {
        if ($Lines[$index] -match "^\s*$([regex]::Escape($Key))\s*=") {
            $Lines[$index] = "$Key = $Value"
            return
        }
    }

    $Lines.Insert($sectionEnd, "$Key = $Value")
}

function Get-SourceFileMap([string]$Root) {
    $map = @{}
    if (-not (Test-Path -LiteralPath $Root)) {
        return $map
    }

    foreach ($file in Get-ChildItem -LiteralPath $Root -File -Recurse) {
        if ($file.FullName -match '[\\/]__pycache__[\\/]' -or $file.Extension -eq ".pyc") {
            continue
        }
        $relative = $file.FullName.Substring($Root.Length).TrimStart("\", "/").Replace("\", "/")
        $map[$relative] = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash
    }
    return $map
}

function Add-SkillDifferences(
    [System.Collections.Generic.List[string]]$Failures,
    [string]$SkillName,
    [string]$Source,
    [string]$Target
) {
    $sourceMap = Get-SourceFileMap $Source
    $targetMap = Get-SourceFileMap $Target
    $paths = @($sourceMap.Keys + $targetMap.Keys | Sort-Object -Unique)

    foreach ($path in $paths) {
        if (-not $sourceMap.ContainsKey($path)) {
            $Failures.Add("Live skill '$SkillName' has an unrecorded source file: $path")
        } elseif (-not $targetMap.ContainsKey($path)) {
            $Failures.Add("Live skill '$SkillName' is missing: $path")
        } elseif ($sourceMap[$path] -ne $targetMap[$path]) {
            $Failures.Add("Skill '$SkillName' differs: $path")
        }
    }
}

function Get-ClaudePointerText {
    # Claude Code reads CLAUDE.md, not AGENTS.md, and supports an @path import.
    # So Claude never gets its own copy of the rulebook - it points at the real one.
    # HTML comments are stripped before Claude loads the file, so they cost nothing.
    $text = @"
<!--
  DO NOT EDIT THIS FILE.

  Ben's standing instructions are shared between Claude, Codex, and any other
  agent. The one real copy lives at:

      $portableAgents

  To change a standing rule, edit that file, then run:

      powershell -NoProfile -ExecutionPolicy Bypass -File $(Join-Path $PSScriptRoot 'workspace.ps1') -Action restore-instructions -Apply

  Editing this file directly makes Claude and Codex disagree without anyone
  noticing. That has already happened once.
-->

@$portableAgents
"@
    return $text.Replace("`r`n", "`n")
}

function Add-ClaudeDifferences([System.Collections.Generic.List[string]]$Failures, [System.Collections.Generic.List[string]]$Warnings) {
    $liveClaude = Join-Path $ClaudeHome "CLAUDE.md"

    if (-not (Test-Path -LiteralPath $liveClaude)) {
        $Failures.Add("Claude's CLAUDE.md is missing, so Claude is running with no standing instructions.")
        return
    }

    # Strip HTML comments: Claude ignores them, so they must not count as instructions.
    $stripped = [regex]::Replace((Get-Content -LiteralPath $liveClaude -Raw), '(?s)<!--.*?-->', '')
    $lines = @($stripped -split "\r?\n" | Where-Object { $_.Trim() })
    $expected = "@$portableAgents"

    if ($lines -notcontains $expected) {
        $Failures.Add("Claude's CLAUDE.md does not import the shared rulebook. It should contain the line: $expected")
    }

    foreach ($line in ($lines | Where-Object { $_ -ne $expected })) {
        $Failures.Add("Claude's CLAUDE.md carries an instruction of its own, which will drift from the shared rulebook: $($line.Trim())")
    }

    # User-level rules load into every Claude session too, and are invisible to Codex.
    $rulesDir = Join-Path $ClaudeHome "rules"
    if (Test-Path -LiteralPath $rulesDir) {
        $ruleFiles = @(Get-ChildItem -LiteralPath $rulesDir -Filter *.md -Recurse -ErrorAction SilentlyContinue)
        if ($ruleFiles.Count -gt 0) {
            $Warnings.Add("$($ruleFiles.Count) personal rule file(s) in $rulesDir load into every Claude session but are invisible to Codex.")
        }
    }

    $localMd = Join-Path $ClaudeHome "CLAUDE.local.md"
    if ((Test-Path -LiteralPath $localMd) -and (Get-Item -LiteralPath $localMd).Length -gt 0) {
        $Warnings.Add("CLAUDE.local.md exists and loads for Claude only. Codex cannot see it.")
    }
}

function Invoke-Check {
    $failures = [System.Collections.Generic.List[string]]::new()
    $warnings = [System.Collections.Generic.List[string]]::new()
    $liveAgents = Join-Path $CodexHome "AGENTS.md"
    $liveOverride = Join-Path $CodexHome "AGENTS.override.md"
    $liveConfig = Join-Path $CodexHome "config.toml"
    $liveSkills = Join-Path $CodexHome "skills"

    if ((Test-Path -LiteralPath $liveOverride) -and (Get-Item -LiteralPath $liveOverride).Length -gt 0) {
        $failures.Add("A non-empty AGENTS.override.md is hiding the recorded global instructions.")
    }

    if (-not (Test-Path -LiteralPath $liveAgents)) {
        $failures.Add("The live global AGENTS.md is missing.")
    } elseif ((Get-FileHash -LiteralPath $portableAgents).Hash -ne (Get-FileHash -LiteralPath $liveAgents).Hash) {
        $failures.Add("The live global instructions and recovery copy differ.")
    }

    if (-not (Test-Path -LiteralPath $liveConfig)) {
        $failures.Add("The live config.toml is missing.")
    } else {
        $expected = Read-SimpleTomlValues $portableConfig
        $actual = Read-SimpleTomlValues $liveConfig
        foreach ($key in $expected.Keys) {
            if (-not $actual.ContainsKey($key)) {
                $failures.Add("The live config is missing portable setting '$key'.")
            } elseif ($actual[$key] -ne $expected[$key]) {
                $failures.Add("Portable setting '$key' differs from the live config.")
            }
        }
    }

    foreach ($skill in Get-ChildItem -LiteralPath $portableSkills -Directory) {
        Add-SkillDifferences $failures $skill.Name $skill.FullName (Join-Path $liveSkills $skill.Name)
    }

    Add-ClaudeDifferences $failures $warnings

    foreach ($file in Get-ChildItem -LiteralPath $repoRoot -File -Recurse -Force) {
        if ($file.FullName -like "$(Join-Path $repoRoot '.git')\*") {
            continue
        }
        $relative = $file.FullName.Substring($repoRoot.Length).TrimStart("\", "/").Replace("\", "/")
        if ($relative -match '(^|/)(auth\.json|\.env(\..*)?|credentials\.[^/]+|secrets\.[^/]+)$' -or
            $relative -match '(^|/)(chat-logs|transcripts|sessions|logs|memories|__pycache__|cache|\.cache)/' -or
            $relative -match '\.(pem|key|p12|pfx|pyc|log)$') {
            $failures.Add("Private or generated file is present in the recovery folder: $relative")
        }
    }

    if (-not (Test-Path -LiteralPath (Join-Path $repoRoot ".git"))) {
        $warnings.Add("This folder does not have Git change history yet.")
    } else {
        $origin = git -C $repoRoot remote get-url origin 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $origin) {
            $warnings.Add("The private GitHub backup is not connected yet.")
        }
        $status = git -C $repoRoot status --porcelain
        if ($status) {
            $warnings.Add("This recovery folder has changes that are not committed yet.")
        }
    }

    foreach ($failure in $failures) {
        Write-Host "FAIL: $failure" -ForegroundColor Red
    }
    foreach ($warning in $warnings) {
        Write-Host "NOTE: $warning" -ForegroundColor Yellow
    }

    if ($failures.Count -gt 0) {
        Write-Host "FAIL" -ForegroundColor Red
        return 1
    }
    if ($warnings.Count -gt 0) {
        Write-Host "PARTIAL" -ForegroundColor Yellow
        return 2
    }

    Write-Host "PASS" -ForegroundColor Green
    return 0
}

function Invoke-Restore {
    param([switch]$InstructionsOnly)

    if (-not $Apply) {
        if ($InstructionsOnly) {
            Write-Host "Preview only. This restores instructions and managed skills; configuration is preserved byte-for-byte:"
        } else {
            Write-Host "Preview only. This restores instructions, portable settings, and personal skills to:"
        }
        Write-Host "  $CodexHome"
        Write-Host "It will preserve the current files in a timestamped backup first."
        Write-Host "Run again with -Action $Action -Apply to continue."
        return 0
    }

    $override = Join-Path $CodexHome "AGENTS.override.md"
    if ((Test-Path -LiteralPath $override) -and (Get-Item -LiteralPath $override).Length -gt 0) {
        throw "A non-empty AGENTS.override.md would hide the restored instructions. Resolve it manually first."
    }

    New-Item -ItemType Directory -Path $CodexHome -Force | Out-Null
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backupRoot = Join-Path $CodexHome "backups\codex-workspace-$stamp"
    New-Item -ItemType Directory -Path $backupRoot -Force | Out-Null

    $liveAgents = Join-Path $CodexHome "AGENTS.md"
    $liveConfig = Join-Path $CodexHome "config.toml"
    $liveSkills = Join-Path $CodexHome "skills"

    if (Test-Path -LiteralPath $liveAgents) {
        Copy-Item -LiteralPath $liveAgents -Destination (Join-Path $backupRoot "AGENTS.md")
    }
    if (Test-Path -LiteralPath $liveConfig) {
        Copy-Item -LiteralPath $liveConfig -Destination (Join-Path $backupRoot "config.toml")
    }

    Copy-Item -LiteralPath $portableAgents -Destination $liveAgents -Force

    # Claude gets a pointer, not a copy, so its instructions cannot drift.
    New-Item -ItemType Directory -Path $ClaudeHome -Force | Out-Null
    $liveClaude = Join-Path $ClaudeHome "CLAUDE.md"
    if (Test-Path -LiteralPath $liveClaude) {
        Copy-Item -LiteralPath $liveClaude -Destination (Join-Path $backupRoot "CLAUDE.md")
    }
    [System.IO.File]::WriteAllText($liveClaude, (Get-ClaudePointerText), [System.Text.UTF8Encoding]::new($false))

    if (-not $InstructionsOnly) {
        $lines = [System.Collections.Generic.List[string]]::new()
        if (Test-Path -LiteralPath $liveConfig) {
            foreach ($line in Get-Content -LiteralPath $liveConfig -Encoding UTF8) {
                $lines.Add($line)
            }
        }
        $expected = Read-SimpleTomlValues $portableConfig
        foreach ($entry in $expected.GetEnumerator()) {
            $parts = $entry.Key.Split("|", 2)
            Set-SimpleTomlValue $lines $parts[0] $parts[1] $entry.Value
        }
        [System.IO.File]::WriteAllLines($liveConfig, $lines, [System.Text.UTF8Encoding]::new($false))
    }

    New-Item -ItemType Directory -Path $liveSkills -Force | Out-Null
    $resolvedSkillsRoot = [System.IO.Path]::GetFullPath($liveSkills).TrimEnd("\") + "\"
    foreach ($skill in Get-ChildItem -LiteralPath $portableSkills -Directory) {
        $target = Join-Path $liveSkills $skill.Name
        $resolvedTarget = [System.IO.Path]::GetFullPath($target)
        if (-not $resolvedTarget.StartsWith($resolvedSkillsRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
            throw "Unsafe skill target: $resolvedTarget"
        }
        if (Test-Path -LiteralPath $target) {
            $skillBackupRoot = Join-Path $backupRoot "skills"
            New-Item -ItemType Directory -Path $skillBackupRoot -Force | Out-Null
            Move-Item -LiteralPath $target -Destination (Join-Path $skillBackupRoot $skill.Name)
        }
        Copy-Item -LiteralPath $skill.FullName -Destination $liveSkills -Recurse
    }

    Write-Host "Restored. Previous files are preserved at:"
    Write-Host "  $backupRoot"
    return Invoke-Check
}

function Invoke-RestoreMemoryUse {
    if (-not $Apply) {
        Write-Host "Preview only. This will restore only the managed Codex memory-use setting and shared rulebook to:"
        Write-Host "  $CodexHome"
        Write-Host "It will preserve the current files in a timestamped backup first."
        Write-Host "Run again with -Action restore-memory -Apply to continue."
        return 0
    }

    $override = Join-Path $CodexHome "AGENTS.override.md"
    if ((Test-Path -LiteralPath $override) -and (Get-Item -LiteralPath $override).Length -gt 0) {
        throw "A non-empty AGENTS.override.md would hide the restored instructions. Resolve it manually first."
    }

    $liveAgents = Join-Path $CodexHome "AGENTS.md"
    $liveConfig = Join-Path $CodexHome "config.toml"
    if (-not (Test-Path -LiteralPath $liveConfig)) {
        throw "The live config.toml is missing. Refusing a selective restore that could create an incomplete configuration."
    }

    $expected = Read-SimpleTomlValues $portableConfig
    $memoryKey = "memories|use_memories"
    if (-not $expected.ContainsKey($memoryKey)) {
        throw "The portable memory-use setting is missing."
    }

    New-Item -ItemType Directory -Path $CodexHome -Force | Out-Null
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backupRoot = Join-Path $CodexHome "backups\codex-memory-use-$stamp"
    New-Item -ItemType Directory -Path $backupRoot -Force | Out-Null

    if (Test-Path -LiteralPath $liveAgents) {
        Copy-Item -LiteralPath $liveAgents -Destination (Join-Path $backupRoot "AGENTS.md")
    }
    Copy-Item -LiteralPath $liveConfig -Destination (Join-Path $backupRoot "config.toml")

    Copy-Item -LiteralPath $portableAgents -Destination $liveAgents -Force

    $lines = [System.Collections.Generic.List[string]]::new()
    foreach ($line in Get-Content -LiteralPath $liveConfig -Encoding UTF8) {
        $lines.Add($line)
    }
    Set-SimpleTomlValue $lines "memories" "use_memories" $expected[$memoryKey]
    [System.IO.File]::WriteAllLines($liveConfig, $lines, [System.Text.UTF8Encoding]::new($false))

    Write-Host "Restored only the managed Codex memory-use setting and shared rulebook. Previous files are preserved at:"
    Write-Host "  $backupRoot"
    return 0
}

if ($Action -eq "restore" -or $Action -eq "restore-instructions") {
    exit (Invoke-Restore -InstructionsOnly:($Action -eq "restore-instructions"))
}

if ($Action -eq "restore-memory") {
    exit (Invoke-RestoreMemoryUse)
}

exit (Invoke-Check)
