import './gaming-preflight.mjs';
import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('work/browser',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push({url:page.url(),stack:e.stack}));
await page.goto(process.env.ROOKERY_URL??'http://127.0.0.1:8790/');
await page.getByRole('heading',{name:'Check an editable encounter map assembled from individual assets'}).waitFor();
await page.screenshot({path:'work/browser/desktop.png',fullPage:false});
await page.getByRole('textbox',{name:'Search needs and capabilities'}).fill('provenance');
await page.getByRole('button',{name:'Search',exact:true}).click();
await page.getByRole('heading',{name:'Crossref REST API'}).waitFor();
await page.getByRole('link',{name:'Crossref REST API',exact:true}).click();
await page.getByRole('heading',{name:'Inputs',exact:true}).count();
await page.getByText('DOI and publication metadata lookup.',{exact:false}).first().waitFor();
await page.screenshot({path:'work/browser/entry.png',fullPage:false});
await page.goto((process.env.ROOKERY_URL??'http://127.0.0.1:8790/')+'connect');
await page.getByRole('heading',{name:'Register an agent',exact:true}).waitFor();
await page.screenshot({path:'work/browser/connect.png',fullPage:false});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,hasTouch:true});
await mobile.goto(process.env.ROOKERY_URL??'http://127.0.0.1:8790/');
await mobile.getByRole('heading',{name:'Check an editable encounter map assembled from individual assets'}).waitFor();
await mobile.screenshot({path:'work/browser/mobile.png',fullPage:false});
const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await page.goto(process.env.ROOKERY_URL??'http://127.0.0.1:8790/');
await page.keyboard.press('Tab');const first=await page.locator(':focus').textContent();await page.keyboard.press('Enter');const skip=await page.locator(':focus').getAttribute('id');
console.log(JSON.stringify({browser:'installed Chrome',desktop:[1440,1000],mobile:[390,844],mobileHorizontalOverflow:overflow,firstTab:first,skipFocus:skip,pageErrors:errors,webMcpSupported:await page.evaluate(()=>!!document.modelContext)},null,2));
await writeFile('work/browser/errors.json',JSON.stringify(errors,null,2));
if(overflow||errors.length||skip!=='main')process.exitCode=1;
await browser.close();
