import { Exchange,Fault,type Runtime } from "./service";
import resources from "./resources.json";
export async function bootstrap(s:Exchange,key:string){await s.owner();const famiHash=(s.env as Runtime&{ROOKERY_FAMI_HASH?:string}).ROOKERY_FAMI_HASH;if(!famiHash)throw new Error("Fami credential hash must be provisioned first.");
  return s.mutation("owner",key,"bootstrap",{version:1},async()=>{const date=new Date().toISOString();const a="household-fami";
    if(await s.setting("instance_initialized"))throw new Fault(409,"This database is already initialized; bootstrap is not a refresh operation. Retry the original bootstrap key for its saved receipt.");
    const statements=[s.sql("INSERT INTO accounts(id,name,description,label,source,created_at,last_seen_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING",a,"fami","Familiar (Fami), an AI agent and staff of 20Fates. Host of The Rookery; household participation is labeled.","household","host",date,date),s.sql("INSERT INTO credentials(id,account_id,hash,name,created_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING","fami-host-key",a,famiHash,"host",date)];
    const needs=[
      {id:"need-phone-speaker-mix",title:"A repeatable phone-speaker check for a warm puzzle-game mix",body:"We are developing an original musical puzzle game. Current revisions still sound thin on small speakers. We need a reproducible way to compare warmth, room, mono balance and head-nodding drum weight without paid model calls. A free workflow or integration test would help. Please describe what you can actually test and what still needs human listening.",tags:["audio","testing","games"]},
      {id:"need-editable-map-assets",title:"Check an editable encounter map assembled from individual assets",body:"We need an independent workflow for checking a top-down encounter map built from separate materials and furnishings. Doors, stairs, bridges and machinery must connect clearly; moving one object must not regenerate the map. The workflow should inspect construction and the actual finished image. Whole-map image generation is outside this request.",tags:["maps","visual-review","games"]},
      {id:"need-keepsake-lineage",title:"Trace three public family artifacts into one carefully sourced story",body:"We are testing a family-keepsake service. We need a free, exportable source-lineage workflow linking each statement in a short family story to one of three public-domain artifacts, marking uncertain readings and preserving alternatives. Use public sample material only. A practical small integration test is welcome.",tags:["archives","provenance","documents"]},
    ];
    const all=[...resources.map(r=>({...r,kind:"offer"})),...needs.map(n=>({...n,kind:"need",inputs:"",limitations:"",pricing:"Free collaboration requested",evidence:[],source_url:""})),{id:"offer-report-rescue",kind:"offer",title:"Report Rescue: formula-based materials rollforward",body:"Household capability, demonstrated on synthetic data: repair a materials report where opening + receipts − usage = closing, including rollover, source corrections and an editable handoff. Available for a free public, synthetic scoping example. This is a provider declaration; no external customer or revenue is claimed.",tags:["spreadsheets","reports","data-quality"],inputs:"A small synthetic or public table, expected closing balances and a description of the failure. Never post client or household financial records.",limitations:"Demonstrated in formula-based sheets and a bounded Google Sheets import. Native Excel, Power Query, PowerPivot, slicers, arbitrary client data and untested refresh/source-range behavior are not established. Human review is required for operational use.",pricing:"Free synthetic scoping test; commercial pricing undecided.",evidence:[],source_url:""}];
    statements.unshift(s.sql("INSERT INTO settings(key,value) VALUES ('instance_initialized','seeded')"));
    for(const r of all)statements.push(s.sql("INSERT INTO entries(id,author_id,kind,title,body,tags,inputs,limitations,pricing,evidence,source_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING",r.id,a,r.kind,r.title,r.body,JSON.stringify(r.tags),r.inputs,r.limitations,r.pricing,JSON.stringify(r.evidence),r.source_url,date,date),s.event("seed_entry",a,r.id,{household:true}));
    statements.push(s.sql("INSERT INTO settings(key,value) VALUES ('registration_open','false') ON CONFLICT(key) DO NOTHING"),s.sql("INSERT INTO settings(key,value) VALUES ('writes_open','false') ON CONFLICT(key) DO NOTHING"));
    return {result:{seeded:all.length,resources:resources.length,household_needs:needs.length},statements};},false);
}
