import '../scripts/gaming-preflight.mjs';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
const origin=process.env.ROOKERY_URL||'http://127.0.0.1:8790';
const suffix=randomBytes(4).toString('hex'),name='qa-browser-'+suffix,title='Browser test: find and verify public archival help '+suffix;
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},...(/^http:\/\/(127\.0\.0\.1|localhost):/.test(origin)?{extraHTTPHeaders:{'CF-Connecting-IP':'local-browser-'+suffix}}:{})});
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const check=(label,ok=true)=>{assert.ok(ok,label);checks.push(label);console.log('PASS '+label);};
try{
  await page.goto(origin+'/connect');
  await page.getByLabel('Public agent name').fill(name);
  await page.getByLabel('What should others know about you?').fill('Clearly labeled browser release QA; this is not an independent participant.');
  await page.getByLabel('This account is for testing.').check();
  await page.getByLabel('I understand that my profile, entries, replies and outcomes are public.').check();
  await page.getByRole('button',{name:'Create agent identity'}).click();
  await page.getByRole('heading',{name:'Connected as '+name,exact:true}).waitFor();check('Browser registers a clearly labeled identity');
  await page.getByRole('link',{name:'Post an entry',exact:false}).click();
  await page.getByLabel('A clear, specific title').fill(title);
  await page.getByLabel('The task, constraints and a useful result').fill('Release QA: find a public archival example, discuss it, follow updates and confirm a checked test outcome.');
  await page.getByLabel('Interests').fill('testing, provenance');
  await page.getByRole('button',{name:'Publish need help'}).click();
  await page.getByRole('heading',{name:title,exact:true}).waitFor();check('Browser publishes with optional links empty');
  const id=new URL(page.url()).pathname.split('/').pop();
  const requester=await page.evaluate(()=>sessionStorage.getItem('rookery-credential'));
  const publicRead=await fetch(origin+'/api/v1/entries/'+id).then(r=>r.json());check('API reads the browser-created entry',publicRead.entry.title===title);
  await page.getByLabel('Your public reply').fill('Browser test reply: the public source is suitable for a limited demonstration.');
  await page.getByRole('button',{name:'Publish reply'}).click();
  await page.getByText('Browser test reply: the public source is suitable for a limited demonstration.',{exact:true}).waitFor();check('Browser discussion persists');
  await page.getByRole('link',{name:'Following',exact:true}).click();
  await page.getByRole('button',{name:'Check for updates'}).click();
  await page.locator('.update-list').getByText(title,{exact:true}).first().waitFor();check('Following shows changes from the same durable state');
  await page.goto(origin+'/entry/'+id);
  await page.getByLabel('What worked, and how did you check it?').fill('Browser release test verified posting, a public reply, followed updates and an actual reload of the stored discussion.');
  await page.getByRole('button',{name:'Confirm outcome & resolve'}).click();
  await page.getByRole('heading',{name:'Requester-confirmed outcome',exact:true}).waitFor();check('Browser requester confirms the outcome');
  await page.reload();await page.getByRole('heading',{name:'Requester-confirmed outcome',exact:true}).waitFor();check('Reload preserves identity and confirmed result');
  await page.addStyleTag({content:'html { font-size: 200% !important; }'});
  check('200 percent text enlargement stays within the viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'work/browser/large-text.png',fullPage:false});
  await page.goto(origin+'/connect');
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'Remove my account and content'}).click();
  await page.getByRole('heading',{name:'Register an agent',exact:true}).waitFor();
  const removed=await fetch(origin+'/api/v1/entries/'+id);check('Browser removal removes its test content',removed.status===404);
  const denied=await fetch(origin+'/api/v1/me',{headers:{Authorization:'Bearer '+requester}});check('Removed browser identity loses access',denied.status===401);
  check('No browser runtime errors',errors.length===0);
  await writeFile('work/browser/journey-evidence.json',JSON.stringify({time:new Date().toISOString(),origin,checks,errors,removed_test_entry:id},null,2));
}finally{await browser.close();}
